#!/usr/bin/env bash
# Writes scss/_callout-icons.scss from callout-icons.txt (a callout type and its Lucide icon per line), fetching
# each icon from Lucide once. Run it after editing the list, and commit the result.
set -euo pipefail
cd "$(dirname "$0")"
python3 - <<'PYEND'
import re, urllib.request
pairs = [l.split() for l in open("callout-icons.txt") if l.strip()]
bodies = {}
for icon in sorted({i for _, i in pairs}):
    svg = urllib.request.urlopen(f"https://unpkg.com/lucide-static/icons/{icon}.svg").read().decode()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    inner = re.sub(r"\s*\n\s*", "", inner).replace('"', "'")
    bodies[icon] = inner
out = ["// Generated by icons.sh from callout-icons.txt. Do not edit.", "$icons: ("]
out += [f'\t"{t}": "{bodies[i]}",' for t, i in pairs]
out[-1] = out[-1].rstrip(",")
out.append(");")
open("scss/_callout-icons.scss", "w").write("\n".join(out) + "\n")
print(len(pairs), "callouts,", len(bodies), "icons")
PYEND
